# GitHub Action for PHP with extensions
name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:
    name: Linux CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php: ['7.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install libuv and PHP build tools
        run: |
          sudo apt update
          sudo apt-get install libuv1-dev php-pear
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: '7.4'
          extensions: mbstring, simplexml, dom, xdebug
          coverage: xdebug
      - name: Build and install PHP-UV extension
        run: |
          sudo pecl channel-update pecl.php.net
          sudo pecl install uv-beta
      - name: Add uv.so to php.ini
        run: sudo echo "extension=uv.so" >> "$(php -r 'echo php_ini_loaded_file();')"
      - name: Install dependencies
        run: composer install
      - name: Test with phpunit
        run: vendor/bin/phpunit -d zend.enable_gc=0 --coverage-clover=coverage/phpunit/clover.xml
      - name: Submit code coverage
        run: bash <(curl -s https://codecov.io/bash)

  linux_php8:
    name: Linux CI - no libuv
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php: ['8']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: '8'
          extensions: mbstring, simplexml, dom
      - name: Install dependencies
        run: composer install
      - name: Test with phpunit
        run: vendor/bin/phpunit -d zend.enable_gc=0 --coverage-clover=coverage/phpunit/clover.xml
      - name: Submit code coverage
        if: ${{ success() }} || ${{ failure() }}
        run: bash <(curl -s https://codecov.io/bash)
